import Foundation

// Non-private compatibility fixture generated by the same encoder as the app.
let destination = URL(fileURLWithPath: CommandLine.arguments[1])
let png = Data(base64Encoded: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=")!
let fixtureItems: [CaptureItem] = [
    .text("甲\n2026年09月30日 10:00\n看这张图\n"),
    .text("\n乙\n2026年09月30日 10:00\n[图片]\n"),
    .asset(png, name: "原图.png", fileExtension: "png"),
    .text("甲\n2026年09月30日 10:01\n[文件] 笔记.txt\n"),
    .asset(Data("保留原始内容\n".utf8), name: "笔记.txt", fileExtension: "txt")
]
let textOnly = CaptureArchive.plainText(from: fixtureItems)
precondition(textOnly == "甲\n2026年09月30日 10:00\n看这张图\n\n乙\n2026年09月30日 10:00\n[图片]\n甲\n2026年09月30日 10:01\n[文件] 笔记.txt\n")
precondition(!textOnly.contains("原图.png") && !textOnly.contains("保留原始内容"))
try CaptureArchive.write(items: fixtureItems, device: "synthetic-test", to: destination)
do {
    try CaptureArchive.write(items: [], device: "test", to: destination)
    fatalError("Empty clipboard must fail")
} catch CaptureFailure.invalid { }
print("Swift capture fixture written; validate using Python next.")
